redis:
  replica:
    replicaCount: 4
  master:
    service:
      ports:
        redis: 5555
    resources:
      limits:
        memory: 2148Mi
        cpu: "2"
      requests:
        memory: 1000Mi
        cpu: "1"
    sentinel:
      enabled: true