redis:
  auth:
    enabled: false
    password: abc123xyz
  commonConfiguration: |-
    appendonly no
    save ""
  master:
    persistence:
      enabled: false
    resources:
      limits:
        memory: 4096Mi
        cpu: "2"
  replica:
    persistence:
      enabled: false
      resources:
        limits:
          memory: 4096Mi
          cpu: "2"
  sentinel:
    enabled: true
